version: '3.9'

# -----------------------------------------------------------------------------
# This compose file is **not required** for normal local development because the
# project defaults to SQLite database files (`smartwallet_dev.db` &
# `smartwallet_test.db`).
#
# The Postgres and Redis services below are provided as a **future-ready** setup
# once we migrate from SQLite to PostgreSQL, or if you prefer to run Postgres
# locally right now. The backend will automatically use Postgres if you export
# a `DATABASE_URL` pointing at one of these containers.
#
# Usage (optional):
#   # Start Postgres + Redis
#   docker compose -f docker-compose.db.yml up -d postgres-dev redis
#
#   # Run migrations against Postgres
#   export DATABASE_URL=postgresql://devuser:devpass@localhost:5432/smartwallet_dev
#   alembic upgrade head
#
#   # Stop and remove containers
#   docker compose -f docker-compose.db.yml down -v
# -----------------------------------------------------------------------------

services:
  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: smartwallet_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: smartwallet_test
    ports:
      - "55432:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres-dev-data:
  postgres-test-data: 