version: "3.9"

# -----------------------------------------------------------------------------
# Minimal Compose stack for running the *backend* test-suite.
# It purposely omits the frontend and other services to keep the feedback loop
# fast. The backend itself runs locally (pytest) while this file only provides
# the infrastructure dependencies (Postgres + Redis).
# -----------------------------------------------------------------------------

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: postgres-test
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: smartwallet_test
    ports:
      - "55432:5432"  # expose on a non-conflicting host port
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d smartwallet_test"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"  # reuse default port; override via REDIS_URL if needed
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres-test-data: