version: '3.9'

services:
  backend:
    build:
      context: ./backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.ci
    depends_on:
      - backend
    ports:
      - "3000:80" 