version: "3.9"

# -----------------------------------------------------------------------------
# CI Compose – extends the main docker-compose.yml for parity while applying
# CI-specific overrides (no live-reload volumes, deterministic build commands).
# -----------------------------------------------------------------------------

services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    # Disable bind mounts, use image built from context for reproducibility
    volumes: []
    env_file: []
    environment:
      # Database configuration
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_SERVER: postgres-dev
      POSTGRES_PORT: 5432
      POSTGRES_DB: smartwallet_dev
      # Security configuration
      JWT_SECRET_KEY: insecure-test-key
      JWT_ALGORITHM: HS256
      BCRYPT_ROUNDS: 4
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      # Redis configuration
      REDIS_URL: redis://redis:6379/0
      # Application configuration
      ENVIRONMENT: development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    volumes: []
    env_file: []
    # Build static artefacts then serve via the same container for smoke tests
    command: >-
      sh -c "npm ci --no-audit --fund=false \
             && npm run build \
             && npx serve -s build -l 3000"

  postgres-dev:
    extends:
      file: docker-compose.yml
      service: postgres-dev

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  mailhog:
    extends:
      file: docker-compose.yml
      service: mailhog

volumes:
  postgres-dev-data:
