[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "smartwalletfx"
version = "0.1.0"
description = "Smart Wallet FX Trading Bot"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn",
    "pytest",
    "httpx",
    "black",
    "flake8",
    "isort",
]

[tool.setuptools]
packages = ["app"]

[tool.pytest.ini_options]
pythonpath = [
    "."
]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
addopts = "-v --cov=app --cov-report=term-missing"

[tool.flake8]
exclude = [
    "venv",
    "venv/*",
    ".venv",
    ".venv/*",
    ".git",
    "__pycache__",
    "build",
    "dist"
]
max-line-length = 88
extend-ignore = ["E203"]

[tool.black]
line-length = 88
target-version = ["py313"]
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/venv/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
skip = ["venv"] 