[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "smartwalletfx"
version = "0.1.0"
description = "Smart Wallet FX Trading Bot"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn",
    "pytest",
    "httpx",
]

[tool.setuptools]
packages = ["app"]

[tool.pytest.ini_options]
pythonpath = [
    "."
]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
addopts = "-v --cov=app --cov-report=term-missing"

[tool.flake8]
exclude = ["venv"] 