"""add portfolio_snapshot_cache table

Revision ID: 0002_add_portfolio_snapshot_cache_table
Revises: 0001_init
Create Date: 2025-06-11 11:18:39.261246

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_add_portfolio_snapshot_cache_table"
down_revision: Union[str, None] = "0001_init"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_snapshot_cache",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_address", sa.String(length=64), nullable=False),
        sa.Column("from_ts", sa.BigInteger(), nullable=False),
        sa.Column("to_ts", sa.BigInteger(), nullable=False),
        sa.Column("interval", sa.String(length=16), nullable=False),
        sa.Column("limit", sa.Integer(), nullable=False),
        sa.Column("offset", sa.Integer(), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_snapshot_cache_user_address"),
        "portfolio_snapshot_cache",
        ["user_address"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_portfolio_snapshot_cache_user_address"),
        table_name="portfolio_snapshot_cache",
    )
    op.drop_table("portfolio_snapshot_cache")
    # ### end Alembic commands ###
