"""
add_rbac_abac_fields

Revision ID: 0008_add_rbac_abac_fields
Revises: 0007_add_created_at_and_updated_at_to_
Create Date: 2025-07-01 06:00:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0008_add_rbac_abac_fields"
down_revision = "0007_add_created_at_and_updated_at_to_"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("roles", sa.JSON(), nullable=True))
    op.add_column("users", sa.Column("attributes", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "attributes")
    op.drop_column("users", "roles")
    # ### end Alembic commands ###
