"""init

Revision ID: 04075fb91280
Revises:
Create Date: 2025-06-11 10:10:11.377969

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04075fb91280"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_address", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("total_collateral", sa.Float(), nullable=False),
        sa.Column("total_borrowings", sa.Float(), nullable=False),
        sa.Column("total_collateral_usd", sa.Float(), nullable=False),
        sa.Column("total_borrowings_usd", sa.Float(), nullable=False),
        sa.Column("aggregate_health_score", sa.Float(), nullable=True),
        sa.Column("aggregate_apy", sa.Float(), nullable=True),
        sa.Column("collaterals", sa.JSON(), nullable=False),
        sa.Column("borrowings", sa.JSON(), nullable=False),
        sa.Column("staked_positions", sa.JSON(), nullable=False),
        sa.Column("health_scores", sa.JSON(), nullable=False),
        sa.Column("protocol_breakdown", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_timestamp"),
        "portfolio_snapshots",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_user_address"),
        "portfolio_snapshots",
        ["user_address"],
        unique=False,
    )
    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("decimals", sa.Integer(), nullable=True),
        sa.Column("chain", sa.String(), nullable=True),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "current_price_usd",
            sa.Numeric(precision=18, scale=8),
            nullable=True,
        ),
        sa.Column("last_price_update", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tokens_address"), "tokens", ["address"], unique=True)
    op.create_index(op.f("ix_tokens_id"), "tokens", ["id"], unique=False)
    op.create_index(op.f("ix_tokens_symbol"), "tokens", ["symbol"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_groups_id"), "groups", ["id"], unique=False)
    op.create_index(op.f("ix_groups_user_id"), "groups", ["user_id"], unique=False)
    op.create_table(
        "token_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=True),
        sa.Column("price_usd", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_prices_id"), "token_prices", ["id"], unique=False)
    op.create_index(
        op.f("ix_token_prices_timestamp"),
        "token_prices",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_token_prices_token_id"),
        "token_prices",
        ["token_id"],
        unique=False,
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("balance_usd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("balance", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wallets_address"), "wallets", ["address"], unique=True)
    op.create_index(op.f("ix_wallets_id"), "wallets", ["id"], unique=False)
    op.create_index(op.f("ix_wallets_user_id"), "wallets", ["user_id"], unique=False)
    op.create_table(
        "historical_balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=True),
        sa.Column("token_id", sa.Integer(), nullable=True),
        sa.Column("balance", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("balance_usd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_historical_balances_id"),
        "historical_balances",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_balances_timestamp"),
        "historical_balances",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_balances_token_id"),
        "historical_balances",
        ["token_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_balances_wallet_id"),
        "historical_balances",
        ["wallet_id"],
        unique=False,
    )
    op.create_table(
        "token_balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=True),
        sa.Column("token_id", sa.Integer(), nullable=True),
        sa.Column("balance", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("balance_usd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_token_balances_id"), "token_balances", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_token_balances_token_id"),
        "token_balances",
        ["token_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_token_balances_wallet_id"),
        "token_balances",
        ["wallet_id"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=True),
        sa.Column("hash", sa.String(), nullable=True),
        sa.Column("token_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("usd_value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("from_address", sa.String(), nullable=True),
        sa.Column("to_address", sa.String(), nullable=True),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_from_address"),
        "transactions",
        ["from_address"],
        unique=False,
    )
    op.create_index(op.f("ix_transactions_hash"), "transactions", ["hash"], unique=True)
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_transactions_timestamp"),
        "transactions",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_to_address"),
        "transactions",
        ["to_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_token_id"),
        "transactions",
        ["token_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_type"), "transactions", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_wallet_id"),
        "transactions",
        ["wallet_id"],
        unique=False,
    )
    op.create_table(
        "wallet_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallet_groups_group_id"),
        "wallet_groups",
        ["group_id"],
        unique=False,
    )
    op.create_index(op.f("ix_wallet_groups_id"), "wallet_groups", ["id"], unique=False)
    op.create_index(
        op.f("ix_wallet_groups_wallet_id"),
        "wallet_groups",
        ["wallet_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallet_groups_wallet_id"), table_name="wallet_groups")
    op.drop_index(op.f("ix_wallet_groups_id"), table_name="wallet_groups")
    op.drop_index(op.f("ix_wallet_groups_group_id"), table_name="wallet_groups")
    op.drop_table("wallet_groups")
    op.drop_index(op.f("ix_transactions_wallet_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_type"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_token_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_to_address"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_timestamp"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_hash"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_from_address"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_token_balances_wallet_id"), table_name="token_balances")
    op.drop_index(op.f("ix_token_balances_token_id"), table_name="token_balances")
    op.drop_index(op.f("ix_token_balances_id"), table_name="token_balances")
    op.drop_table("token_balances")
    op.drop_index(
        op.f("ix_historical_balances_wallet_id"),
        table_name="historical_balances",
    )
    op.drop_index(
        op.f("ix_historical_balances_token_id"),
        table_name="historical_balances",
    )
    op.drop_index(
        op.f("ix_historical_balances_timestamp"),
        table_name="historical_balances",
    )
    op.drop_index(op.f("ix_historical_balances_id"), table_name="historical_balances")
    op.drop_table("historical_balances")
    op.drop_index(op.f("ix_wallets_user_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_address"), table_name="wallets")
    op.drop_table("wallets")
    op.drop_index(op.f("ix_token_prices_token_id"), table_name="token_prices")
    op.drop_index(op.f("ix_token_prices_timestamp"), table_name="token_prices")
    op.drop_index(op.f("ix_token_prices_id"), table_name="token_prices")
    op.drop_table("token_prices")
    op.drop_index(op.f("ix_groups_user_id"), table_name="groups")
    op.drop_index(op.f("ix_groups_id"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tokens_symbol"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_id"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_address"), table_name="tokens")
    op.drop_table("tokens")
    op.drop_index(
        op.f("ix_portfolio_snapshots_user_address"),
        table_name="portfolio_snapshots",
    )
    op.drop_index(
        op.f("ix_portfolio_snapshots_timestamp"),
        table_name="portfolio_snapshots",
    )
    op.drop_table("portfolio_snapshots")
    # ### end Alembic commands ###
