name: nightly-audit-log-validate

on:
  schedule:
    - cron: '30 2 * * *'  # every day at 02:30 UTC
  workflow_dispatch:

jobs:
  audit-log-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies (validator only)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -q 'pydantic>=2.5'

      - name: Fetch previous day CloudWatch logs (stub)
        run: |
          echo '{"timestamp":"2025-06-20T00:00:00Z","action":"stub_event"}' > logs.jsonl

      - name: Validate logs
        run: |
          source venv/bin/activate
          python - <<'PY'
          import json, sys, pathlib
          from app.utils.audit import validate_audit_event, AuditValidationError
          failures = 0
          for line in pathlib.Path('logs.jsonl').read_text().splitlines():
              if not line.strip():
                  continue
              try:
                  validate_audit_event(json.loads(line))
              except AuditValidationError as exc:
                  print('Invalid audit event:', exc)
                  failures += 1
          if failures:
              sys.exit(1)
          PY

      - name: Slack Notify (stub)
        if: failure()
        run: echo 'Notify Slack – audit validation failed.' 