name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

env:
  PYTHON_VERSION: '3.12'
  CACHE_VERSION: 2  # Increment to invalidate cache

jobs:
  setup:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create virtual environment and install dependencies
        working-directory: ./backend
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          path: backend/.venv
          key: ${{ runner.os }}-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('backend/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-venv-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-venv-

  isort:
    needs: [setup, changes]
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Restore virtualenv
        uses: actions/cache@v4
        with:
          path: backend/.venv
          key: ${{ runner.os }}-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('backend/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-venv-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-venv-

      - name: Run isort
        working-directory: ./backend
        run: |
          source .venv/bin/activate
          isort --check-only --diff .

  black:
    needs: [setup, changes]
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Restore virtualenv
        uses: actions/cache@v4
        with:
          path: backend/.venv
          key: ${{ runner.os }}-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('backend/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-venv-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-venv-

      - name: Run black
        working-directory: ./backend
        run: |
          source .venv/bin/activate
          black --check --diff .

  flake8:
    needs: [setup, changes]
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Restore virtualenv
        uses: actions/cache@v4
        with:
          path: backend/.venv
          key: ${{ runner.os }}-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('backend/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-venv-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-venv-

      - name: Run flake8
        working-directory: ./backend
        run: |
          source .venv/bin/activate
          flake8 . --exclude=.venv,tests,migrations

  test-backend:
    needs: [isort, black, flake8, changes]
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    env:
      ARBITRUM_RPC_URL: "http://localhost:8545"
      TEST_DATABASE_URL: "sqlite:///./smartwallet_test.db"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Restore virtualenv
        uses: actions/cache@v4
        with:
          path: backend/.venv
          key: ${{ runner.os }}-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('backend/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-venv-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-venv-

      - name: Run tests with coverage
        working-directory: ./backend
        run: |
          source .venv/bin/activate
          PYTHONPATH=$(pwd) pytest -v --cov=app --cov-report=xml

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: ./backend/coverage.xml
          flags: backend
          name: backend-coverage

  build-backend:
    needs: [test-backend, changes]
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Restore virtualenv
        uses: actions/cache@v4
        with:
          path: backend/.venv
          key: ${{ runner.os }}-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('backend/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-venv-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-venv-

      - name: Build package
        working-directory: ./backend
        run: |
          source .venv/bin/activate
          python -m build

  deploy-backend:
    needs: [build-backend, changes]
    if: needs.changes.outputs.backend == 'true' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Deploying backend to production..."
          # Add deployment commands here

  build-frontend:
    needs: [isort, black, flake8, changes]
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci --no-audit --fund=false

      - name: Lint frontend
        working-directory: ./frontend
        run: |
          if [ -f package.json ]; then npm run lint --if-present ; fi

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false --no-watchman --ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build

  deploy-frontend:
    needs: [build-frontend, changes]
    if: needs.changes.outputs.frontend == 'true' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy frontend
        run: |
          echo "Deploying frontend to production..."
          # Add deployment commands here

  notify:
    needs: [deploy-backend, build-backend, deploy-frontend]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check workflow status
        id: check
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "color=dc3545" >> $GITHUB_OUTPUT
            echo "icon=❌" >> $GITHUB_OUTPUT
          else
            echo "status=success" >> $GITHUB_OUTPUT
            echo "color=28a745" >> $GITHUB_OUTPUT
            echo "icon=✅" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Deployment Status
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const run_link = `https://github.com/${owner}/${repo}/actions/runs/${context.runId}`;
            const status = "${{ steps.check.outputs.status }}";
            const icon = "${{ steps.check.outputs.icon }}";
            
            const message = `${icon} Workflow ${context.workflow} ${status}\n
            Branch: ${context.ref}
            Commit: ${context.sha}
            Author: ${context.actor}
            Details: ${run_link}`;
            
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: context.issue.number || context.payload.pull_request?.number,
              body: message
            }).catch(e => console.log('No PR/Issue associated with this run'));

      - name: Notify on Success
        if: steps.check.outputs.status == 'success'
        run: |
          echo "✅ CI/CD Pipeline completed successfully!"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "View run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Notify on Failure
        if: steps.check.outputs.status == 'failure'
        run: |
          echo "❌ CI/CD Pipeline failed!"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "View run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Detect path changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  e2e-cypress:
    needs: [build-backend, build-frontend, changes]
    if: needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }} and Cypress cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Cypress dependencies
        working-directory: ./frontend
        run: npm ci --no-audit --fund=false

      - name: Start services via docker-compose
        run: |
          docker compose -f docker-compose.ci.yml up -d --build

      - name: Wait for backend health
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8000/api/v1/health > /dev/null; then
              echo "Backend is up" && break;
            fi
            echo "Waiting for backend..." && sleep 2;
          done

      - name: Run Cypress tests
        working-directory: ./frontend
        run: npx cypress run --browser chrome --headless

      - name: Upload Cypress artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: frontend/cypress/screenshots

      - name: Shutdown docker-compose
        if: always()
        run: docker compose -f docker-compose.ci.yml down 